# Clean Earnings Data

In [18]:
import pandas as pd
import numpy as np

In [ ]:
df_earnings = pd.read_csv('earnings_merged.csv')
df_earnings.info()

<class 'pandas.DataFrame'>
RangeIndex: 2520 entries, 0 to 2519
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ticker        2520 non-null   str
 1   Date          2520 non-null   str
 2   EPS Estimate  2474 non-null   float64
 3   EPS Reported  2470 non-null   float64
 4   Surprise%     2468 non-null   object
dtypes: float64(2), object(1), str(2)
memory usage: 98.6+ KB

In [15]:
df_earnings['Date'] = pd.to_datetime(df_earnings['Date'], utc=True).dt.strftime('%Y-%m-%d')

In [ ]:
df_earnings['Surprise%'] = np.where(df_earnings['EPS Estimate'] != 0,
    ((df_earnings['EPS Reported'] - df_earnings['EPS Estimate']) / abs(df_earnings['EPS Estimate'])) * 100, None)

In [20]:
# display all rows
pd.set_option('display.max_rows', None)

In [24]:
print(df_earnings.isnull().sum())
print("Total rows with missing values:", df_earnings.isnull().any(axis=1).sum())
df_earnings[df_earnings.isnull().any(axis=1)]

Ticker           0
Date             0
EPS Estimate    46
EPS Reported    50
Surprise%       52
dtype: int64
Total rows with missing values: 52

     Ticker        Date  EPS Estimate  EPS Reported Surprise%
417       L  2026-08-03           NaN           NaN       NaN
590    APLD  2026-01-07         -0.21           NaN       NaN
638    COKE  2026-07-29           NaN           NaN       NaN
915   LLYVK  2026-08-06          0.42           NaN       NaN
973     NEU  2026-08-05           NaN           NaN       NaN
1154    JOE  2026-07-22           NaN           NaN       NaN
1203    NHC  2026-08-06           NaN           NaN       NaN
1216   FRHC  2026-05-28           NaN           NaN       NaN
1294    BLX  2026-08-04           NaN           NaN       NaN
1417   CRVL  2026-05-20           NaN           NaN       NaN
1487    DJT  2026-07-31           NaN           NaN       NaN
1518  IMKTA  2026-08-06           NaN           NaN       NaN
1546    SEB  2026-07-27           NaN           NaN       NaN
1570    WMK  2026-08-05           NaN           NaN       NaN
1615    ODC  2026-06-04           NaN           NaN       NaN
1637     TK  2026-08-05           NaN           NaN       NaN
1641  SENEA  2026-06-11           NaN           NaN       NaN
1709   TRST  2026-07-20           NaN           NaN       NaN
1769    NPK  2026-07-24           NaN           NaN       NaN
1776  GLIBK  2026-08-06           NaN           NaN       NaN
1818   ESRT  2026-07-22           NaN           NaN       NaN
1823   KODK  2026-08-10           NaN           NaN       NaN
1829    EVC  2026-08-04           NaN           NaN       NaN
1849    DEC  2026-03-17           NaN           NaN       NaN
1863     TR  2026-07-22           NaN           NaN       NaN
1896   DJCO  2026-08-13           NaN           NaN       NaN
1986   WSBF  2026-02-13           NaN           NaN       NaN
1992   TSBK  2026-07-21           NaN           NaN       NaN
2001   ITIC  2026-08-06           NaN           NaN       NaN
2020   RZLV  2026-10-01           NaN           NaN       NaN
2075    UHT  2026-07-27           NaN           NaN       NaN
2079    ALX  2026-08-03           NaN           NaN       NaN
2091   HIFS  2026-07-17           NaN           NaN       NaN
2108   NVEC  2026-07-22           NaN           NaN       NaN
2120   TIPT  2026-07-29           NaN           NaN       NaN
2136   FRPH  2026-08-05           NaN           NaN       NaN
2137   ANGO  2026-01-06         -0.10           NaN       NaN
2148   FNLC  2026-07-22           NaN           NaN       NaN
2155   FDBC  2026-07-22           NaN           NaN       NaN
2183   RHLD  2026-08-06           NaN           NaN       NaN
2196     TG  2026-08-07           NaN           NaN       NaN
2214    NRC  2026-07-27           NaN           NaN       NaN
2258   BRCC  2026-03-02          0.00         -0.03      None
2305   WALD  2026-01-20         -0.11           NaN       NaN
2367   SIGA  2026-08-04           NaN           NaN       NaN
2390   OFLX  2026-07-29           NaN           NaN       NaN
2414   UTMD  2026-07-23           NaN           NaN       NaN
2432   NLOP  2026-08-05           NaN           NaN       NaN
2475   CMDB  2026-08-07           NaN           NaN       NaN
2478   NXDT  2026-08-13           NaN           NaN       NaN
2484   HAIN  2026-02-09          0.00         -0.03      None
2501    TCX  2026-08-06           NaN           NaN       NaN

In [ ]:
# Drop rows with missing values and round 'Surprise%' to 4 decimal places
df_earnings_modified = df_earnings.dropna()
df_earnings_modified['Surprise%'] = df_earnings_modified['Surprise%'].round(4)

print("Total rows after dropping missing values:", df_earnings_modified.shape[0])
df_earnings_modified.head()

Total rows after dropping missing values: 2468

  Ticker        Date  EPS Estimate  EPS Reported Surprise%
0   AAPL  2026-01-29          2.67          2.84     6.367
1  GOOGL  2026-02-04          2.64          2.82    6.8182
2   GOOG  2026-02-04          2.64          2.82    6.8182
3   TSLA  2026-01-28          0.34          0.24  -29.4118
4   MSFT  2026-01-28          3.92          4.14    5.6122

In [30]:
df_earnings_modified.to_csv('earnings_cleaned.csv', index=False)

In [ ]:
# Load the Russell 3000 ETF fund data and filter it to include only tickers present in the cleaned earnings data
df_russell_shares = pd.read_csv('iShares-Russell-3000-ETF_fund.csv')
df_russell_shares = df_russell_shares[df_russell_shares['Ticker'].isin(df_earnings_modified['Ticker'])]
df_russell_shares.to_csv('iShares-Russell-3000-ETF_fund_cleaned.csv', index=False)